#!/bin/bash
echo "Best Schol" >> '*\\"Best School"\'\\*$\?\*\*\*\*\*:\)'
touch '*\\'"Best School"\'\\*$\?\*\*\*\*\*:\)'
echo "Best School" >> '*\\'"Best School"\'\\*$\?\*\*\*\*\*:\)' 
echo "" >> '*\\'"Best School"\'\\*$\?\*\*\*\*\*:\)' 
