#!/usr/bin/env bash
# Displays information about subdomains

get_subdomain_info() {
    local domain=$1
    local subdomain=$2

    local record=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ {getline; print $4 " " $5}')

    local record_type=$(echo "$record" | cut -d' ' -f1)
    local destination=$(echo "$record" | cut -d' ' -f2)
    
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ $# -eq 1 ]; then

    for sub in "www" "lb-01" "web-01" "web-02"; do
        get_subdomain_info "$1" "$sub"
    done
elif [ $# -eq 2 ]; then

    get_subdomain_info "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
