#!/usr/bin/env bash
# This script transfers a file from the client to a server

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"

if [ "$?" -eq 0 ]; then
    echo "File transferred successfully."
else
    echo "File transfer failed."
    exit 1
fi
