#!/usr/bin/env bash
# This script installs Nginx, configures it to return "Hello World!" at the root URL, and ensures Nginx is running

sudo pt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx restart

sudo ufw allow 'Nginx HTTP'
sudo ufw enable
sudo ufw status
