#!/usr/bin/env bash
# This script installs Nginx, configures it to return "Hello World!" at the root URL,
# sets up a redirection for /redirect_me, and ensures Nginx is running

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure redirection
sudo sed -i '/server_name _;/a \
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }' /etc/nginx/sites-available/default

sudo service nginx restart

sudo ufw allow 'Nginx HTTP'
sudo ufw enable
sudo ufw status
