#!/usr/bin/env bash
# This script installs Nginx, configures it to return "Hello World!" at the root URL,
# sets up a redirection for /redirect_me, creates a custom 404 page,
# and ensures Nginx is running

# Update package lists and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create a simple HTML file to serve
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx
sudo bash -c 'cat > /etc/nginx/sites-available/default << EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOL'

# Restart Nginx to apply changes
sudo service nginx restart

sudo ufw allow 'Nginx HTTP'
sudo ufw enable
sudo ufw status
