#!/usr/bin/env bash
# Configures Nginx to listen on port 80 of all active IPv4 IPs

# Stop nginx service if it's running
service nginx stop

# Configure nginx to listen on port 80
sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:8080 default_server;/listen \[::\]:80 default_server;/' /etc/nginx/sites-available/default

# Ensure the default site is enabled
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Start nginx service
service nginx start
