#!/usr/bin/env bash
# Script configures the server to resolve localhost to 127.00.2 and facebook.com 8.8.8.8

sudo cp /etc/hosts /etc.hosts.backup

sudo sed -i '/localhost/d' /etc/hosts
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
