#!/usr/bin/env bash
# Fixes Apache server to display "Hello Holberton"

# Install Apache if not already installed
sudo apt-get update
sudo apt-get install -y apache2

echo "Hello Holberton" > /var/www/html/index.html

service apache2 start
