#!/usr/bin/env bash
# This script configures Apache to return a page containing "Hello Holberton"

apt-get update
apt-get install -y apache2

echo "Hello Holberton" > /var/www/html/index.html

service apache2 start
