#!/usr/bin/env bash
# This script runs the whoami command as the user specified in the argument

if id "$1" &>/dev/null; then
    sudo -u "$1" whoami
else
    echo "The user $1 does not exist"
    exit 1
fi
